#!/bin/bash
#
# A commit script which is executed by the CI server.
# The workspace at the CI server should be deleted before each build, so make no assumptions about local dependencies however
# global dependencies/PATH modifications/environment variables should be in place.
#
#
# Author: Björn Ingemar Elfström

#Install dependencies for the server.
npm install

#Install dependencies for the client.
cd ./client
npm install

#Go to project root and build and test the project.
cd ..
./build.sh
npm run commit-test-suite
