version: '2'

services:    
    server:
        ports:
            - "8080:8080"
        image: "bjorne14/tictactoe:${VERSION}"
        environment:
            NODE_ENV: production
        depends_on:
            - db
        env_file: .env
    db:
        image: postgres:latest
        environment:
            PGUSER: postgres
            PGPASSWORD: mysecretpassword
            PGDATABASE: postgres
        ports:
            - "5432:5432"
    
